paths:
    data: "../data/gridstates_training.hdf5"
    save_dir: "models"
    plot_dir: "figures"

dataset:
    test_size: 0.2
    batch_size: 128
    augment: true
    uniform_bins: 10

training:
    epochs: 128
    lr: 0.001
    weight_decay: 0.0001
    loss: "SmoothL1Loss"
    optimizer: "AdamW"

model:
    type: "cnn"
    channels: 64
    num_cnn_layers: 3
    num_fc_layers: 2

parameters:
    beta: 0.55
    h: 0.07
